pub const ENV: &str = "ENV";
pub const DB_URI: &str = "DB_URI";
pub const UK_DB_URI: &str = "UK_DB_URI";
pub const KSA_DB_URI: &str = "KSA_DB_URI";
pub const UK: &str = "UK";
pub const KSA: &str = "KSA";
pub const DB_NAME: &str = "DB_NAME";
pub const FIREBASE_CREDENTIALS_BASE64: &str = "FIREBASE_CREDENTIALS_BASE64";
pub const AWS_S3_BUCKET_NAME: &str = "AWS_S3_BUCKET_NAME";
pub const LOCAL_ENV: &str = "local";
pub const PRODUCTION_ENV: &str = "production";
pub const LOCAL_DB_URI: &str = "LOCAL_DB_URI";
pub const SMTP_SERVER_NAME: &str = "SMTP_SERVER_NAME";
pub const SMTP_SERVER_USERNAME: &str = "SMTP_SERVER_USERNAME";
pub const SMTP_SERVER_PASSWORD: &str = "SMTP_SERVER_PASSWORD";
pub const SMTP_SERVER_FROM_EMAIL: &str = "SMTP_SERVER_FROM_EMAIL";
pub const LA_AUTH_TOKEN_SIGNING_KEY_SECRET_NAME: &str = "LA_AUTH_TOKEN_SIGNING_KEY_SECRET_NAME";
pub const RSA_PUBLIC_KEY_SECRET_NAME: &str = "RSA_PUBLIC_KEY_SECRET_NAME";
pub const RSA_PRIVATE_KEY_SECRET_NAME: &str = "RSA_PRIVATE_KEY_SECRET_NAME";
pub const HMAC_KEY_SECRET_NAME: &str = "HMAC_KEY_SECRET_NAME";
pub const TWILIO_AUTH_TOKEN_SIGNING_KEY_SECRET_NAME: &str =
    "TWILIO_AUTH_TOKEN_SIGNING_KEY_SECRET_NAME";
pub const LOCAL_LA_AUTH_TOKEN_SIGNING_KEY: &str = "LOCAL_LA_AUTH_TOKEN_SIGNING_KEY";
pub const LOCAL_TWILIO_AUTH_TOKEN_SIGNING_KEY: &str = "LOCAL_TWILIO_AUTH_TOKEN_SIGNING_KEY";
pub const USERS_COLLECTION: &str = "USERS_COLLECTION";
pub const CALLS_COLLECTION: &str = "CALLS_COLLECTION";
pub const DEVICES_COLLECTION: &str = "DEVICES_COLLECTION";
pub const CLIENT_COLLECTION: &str = "CLIENT_COLLECTION";
pub const MOBILE_DEVICE_INVITATION_COLLECTION: &str = "MOBILE_DEVICE_INVITATION_COLLECTION";
pub const MAX_ALLOWED_RANDOM_DEVICES: &str = "MAX_ALLOWED_RANDOM_DEVICES";
pub const LOCAL_FIREBASE_ACCOUNT_SERVICE_JSON_PATH: &str =
    "LOCAL_FIREBASE_ACCOUNT_SERVICE_JSON_PATH";
pub const LOCAL_PLAY_INTEGRITY_ACCOUNT_SERVICE_JSON_PATH: &str =
    "LOCAL_PLAY_INTEGRITY_ACCOUNT_SERVICE_JSON_PATH";
pub const AWS_PLAY_INTEGRITY_ACCOUNT_SERVICE_JSON_BUCKET_NAME: &str =
    "AWS_PLAY_INTEGRITY_ACCOUNT_SERVICE_JSON_BUCKET_NAME";
pub const AWS_PLAY_INTEGRITY_ACCOUNT_SERVICE_JSON_OBJECT_KEY: &str =
    "AWS_PLAY_INTEGRITY_ACCOUNT_SERVICE_JSON_OBJECT_KEY";
pub const FIREBASE_PROJECT_ID: &str = "FIREBASE_PROJECT_ID";
pub const REDIS_URL: &str = "REDIS_URL";
pub const ROTATE_DEVICES_GROUP_IDS_INTERVAL: &str = "ROTATE_DEVICES_GROUP_IDS_INTERVAL";
pub const BATCH_SIZE: &str = "BATCH_SIZE";
pub const GROUP_DEVICE_COUNT: &str = "GROUP_DEVICE_COUNT";
pub const GROUP_DEVICE_ID_USAGE_COUNT: &str = "GROUP_DEVICE_ID_USAGE_COUNT";
pub const DEVICES_GROUP_SIZE: &str = "DEVICES_GROUP_SIZE";
pub const DEEP_LINK_API_URL: &str = "DEEP_LINK_API_URL";
pub const DEEP_LINK_BRANCHIO_KEY_SECRET_NAME: &str = "DEEP_LINK_BRANCHIO_KEY_SECRET_NAME";
pub const GOOGLE_API_KEYS_URL: &str = "GOOGLE_API_KEYS_URL";
pub const TWILIO_ACCOUNT_SID: &str = "TWILIO_ACCOUNT_SID";
pub const TWILIO_AUTH_TOKEN: &str = "TWILIO_AUTH_TOKEN";
pub const TWILIO_SERVICE_ID: &str = "TWILIO_SERVICE_ID";
pub const ENCLAVE_RSA_KEY_ID: &str = "ENCLAVE_RSA_KEY_ID";
pub const ENCLAVE_HMAC_KEY_ID: &str = "ENCLAVE_HMAC_KEY_ID";
pub const AWS_REGION: &str = "AWS_REGION";
pub const ENCLAVE_TRANSFORM_HASH_API_URL: &str = "ENCLAVE_TRANSFORM_HASH_API_URL";
pub const APPLE_VALIDATE_APP_AUTH_TOKEN: &str = "APPLE_VALIDATE_APP_AUTH_TOKEN";
pub const APPLE_TEAM_ID: &str = "APPLE_TEAM_ID";
pub const APPLE_BUNDLE_ID: &str = "APPLE_BUNDLE_ID";

pub const TEST_RSA_PRIVATE_KEY: &str = "TEST_RSA_PRIVATE_KEY";
pub const TEST_RSA_PUBLIC_KEY: &str = "TEST_RSA_PUBLIC_KEY";
pub const TEST_HMAC_KEY: &str = "TEST_HMAC_KEY";

pub const PRIVATE_SPARKS_CREATED: &str = "private_sparks_created";
